### PR TITLE
Migrated to null safety

### PR DESCRIPTION
**Pull request by pythonhubdev**
The complete codebase and the examples are migrated to the null safe version referencing issue #4.

### CODE REVIEW

**Comment by gbmiranda** [comment]
Nice, I will do some tests and if are ok, I do the merge.

**Comment by pythonhubdev** [comment]
Thanks a lot. I am also working on the Todo's if completed will make a PR.

**Comment by pythonhubdev** [comment]
That's great thanks.

**Comment by gbmiranda** [comment]
Version 0.0.9 with null safety released.

Thank you for the help!

**Pull request merged**
